require('settings')
require('packer-config')
require('color-scheme')
require('mappings')
require('telescope_file_browser')
require('lsp-config')
require('galaxy')
require('format-config')
require('indent-config')
require('scroll-bar')
require('cursor-line')

require('nvim-cmp')
